# Generated by Django 4.0.1 on 2022-02-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PresetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Title', models.CharField(max_length=100)),
                ('video_ID', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambience.preset')),
            ],
        ),
    ]
