# Generated by Django 4.0.1 on 2022-02-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('video_ID', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='presetitem',
            name='isAvailable',
        ),
        migrations.RemoveField(
            model_name='presetitem',
            name='video_ID',
        ),
        migrations.RemoveField(
            model_name='presetitem',
            name='video_Title',
        ),
        migrations.AddField(
            model_name='presetitem',
            name='video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ambience.video'),
        ),
    ]
