# Generated by Django 4.0.1 on 2022-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambience', '0002_video_remove_presetitem_isavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_ID',
            field=models.CharField(max_length=11),
        ),
    ]
